Update installation routines to match upstream

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,26 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+platform=$(get_platform)
+ext="tar.gz"
+if [ "$platform" == "windows" ]; then
+  ext="zip"
+fi
 
-# Download tar.gz file to the download directory
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.${ext}"
+
+# Download archive file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+# Extract contents of archive file into the download directory
+case $platform in
+  windows)
+    unzip "$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not uncompress"
+    ;;
+  *)
+    tar zxvf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not uncompress"
+    ;;
+esac
 
-# Remove the tar.gz file since we don't need to keep it
+# Remove the archive file since we don't need to keep it
 rm "$release_file"
